{% set name = "pypolymlp" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypolymlp-{{ version }}.tar.gz
  sha256: 5bb9c206b87de4709a925f3183475a38ec1eb0fdbf091fcc8ce1b13ce2b74715

build:
  skip: true  # [py<39 or win]
  entry_points:
    - pypolymlp=pypolymlp.api.run_polymlp:run
    - pypolymlp-calc=pypolymlp.api.run_polymlp_calc:run
    - pypolymlp-utils=pypolymlp.api.run_polymlp_utils:run
    - pypolymlp-structure=pypolymlp.api.run_polymlp_str:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - ninja
    - cmake
    - make
    - eigen
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - wheel
    - setuptools >=61.0
    - scikit-build-core
    - setuptools_scm
    - pip
    - pybind11
    - pybind11-global
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - python
    - numpy !=2.0.*
    - scipy
    - pyyaml
    - setuptools >=61.0

test:
  imports:
    - pypolymlp
  requires:
    - pip
  commands:
    - pypolymlp --help
    - pypolymlp-calc --help
    - pypolymlp-utils --help
    - pypolymlp-structure --help
    - pip check

about:
  home: https://github.com/sekocha/pypolymlp
  summary: Generator of polynomial machine learning potentials.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sekocha
